# fly.toml app configuration file generated for biblio-app on 2025-04-02T14:38:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biblio-app'
primary_region = 'arn'

[build]

[env]
  PORT = '3838'

[[services]]
  protocol = 'tcp'
  internal_port = 3838

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
