app = "biblio-app"
primary_region = "arn"

[build]

[env]
  PORT = "3838"

[[services]]
  protocol = "tcp"
  internal_port = 3838

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
